/** @format */

import Navbar from '@/components/UI/Navbar';
import './globals.css';
import { Roboto } from 'next/font/google';
import { SwiperProvider } from '@/common/SwiperContext';

const anybody = Roboto({
	subsets: ['cyrillic'],
	weight: ['300', '400', '500', '700', '900'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='ru'>
			<body className={anybody.className}>
				<Navbar />
				<SwiperProvider>{children}</SwiperProvider>
			</body>
		</html>
	);
}
